// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var element = document.querySelector("#root");

if (element == null) {
  console.log("Root component not exist");
} else {
  ReactDom.render(React.createElement(App.App.make, {}), element);
}

export {
  
}
/* element Not a pure module */
